version: '2'
services:
  app:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: beeper_app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
