version: '2'
services:
  app:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: beeper_app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    env_file:
      - .env
    networks:
      - beeper_network
    depends_on:
      - db
    ports:
      - 8082:80

  db:
    image: mysql:5.7.29
    container_name: beeper_db
    networks:
      - beeper_network
    volumes:
      - ./docker-volumes/db:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  beeper_network:
    driver: bridge
